include($$PWD/src/3rdparty/qjsonwebtoken/qjsonwebtoken.pri)
include($$PWD/src/3rdparty/qstm/test/qstm-test.pri)
include($$PWD/src/3rdparty/qrpc/test/qrpc-test.pri)
include($$PWD/src/3rdparty/qorm/test/qorm-test.pri)
include($$PWD/src/3rdparty/qapr/test/qapr-test.pri)
